# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='model_pic',
            field=models.ImageField(default='profiles/profile.png', upload_to='profiles/'),
        ),
    ]
