# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Folder')),
            ],
        ),
    ]
