# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('website', '0004_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskSpace',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('max_space', models.IntegerField(default=512)),
                ('usage', models.IntegerField(default=0)),
            ],
        ),
    ]
