# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 22:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_auto_20160811_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogsFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogsRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Relationship')),
            ],
        ),
    ]
