# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20160823_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Denied'), (3, 'Removed')], default=0),
        ),
        migrations.AlterField(
            model_name='sharefolder',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Denied'), (3, 'Removed')], default=0),
        ),
    ]
