# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 18:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0010_auto_20160825_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsShareFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='LogsShareFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('share_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ShareFolder')),
            ],
        ),
        migrations.CreateModel(
            name='ShareFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Denied'), (3, 'Removed')], default=0)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='logssharefile',
            name='share_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ShareFile'),
        ),
        migrations.AlterUniqueTogether(
            name='sharefile',
            unique_together=set([('user', 'file')]),
        ),
    ]
